name: Docker pull from dockerhub and docker push to ecr aws

on:
  push:
    branches: [ main ]

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_CI_ACCOUNT_ID: ${{ secrets.AWS_CI_ACCOUNT_ID }}
  AWS_CI_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
  AWS_CI_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
  
  AWS_QA_ACCOUNT_ID: ${{ secrets.AWS_QA_ACCOUNT_ID }}
  AWS_QA_ACCESS_KEY_ID: ${{ secrets.AWS_QA_ACCESS_KEY_ID }}
  AWS_QA_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_SECRET_ACCESS_KEY }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure environments
        run: |
          aws configure set aws_account_id ${AWS_CI_ACCOUNT_ID} --profile prod \
          && aws configure set aws_access_key_id ${AWS_CI_ACCESS_KEY_ID} --profile prod \
          && aws configure set aws_secret_access_key ${AWS_CI_SECRET_ACCESS_KEY} --profile prod \
          && aws configure set aws_account_id ${AWS_QA_ACCOUNT_ID} --profile qa \
          && aws configure set aws_access_key_id ${AWS_QA_ACCESS_KEY_ID} --profile qa \
          && aws configure set aws_secret_access_key ${AWS_QA_SECRET_ACCESS_KEY} --profile qa \
          
      - name: Pull and push to ECR
        run: |
         for row in $(cat ./images-docker/images.json | jq -r '.[] | @base64'); do
              _jq() {
               echo ${row} | base64 --decode | jq -r ${1}
              }
              
              echo $(_jq '.Profile') \
              && echo "PROFILE_AWS=$(cat ./images-docker/images.json | _jq '.Profile' | sed 's/"//g')" >> $GITHUB_ENV \
              && echo $PROFILE_AWS
              done
    
