name: Docker pull from dockerhub and docker push to ecr aws

on:
  push:
    branches: [ main ]

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_CI_ACCOUNT_ID: ${{ secrets.AWS_CI_ACCOUNT_ID }}
  AWS_CI_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
  AWS_CI_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
  
  AWS_QA_ACCOUNT_ID: ${{ secrets.AWS_QA_ACCOUNT_ID }}
  AWS_QA_ACCESS_KEY_ID: ${{ secrets.AWS_QA_ACCESS_KEY_ID }}
  AWS_QA_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_SECRET_ACCESS_KEY }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure environments
        run: |
          aws configure set aws_account_id ${AWS_CI_ACCOUNT_ID} --profile ci \
          && aws configure set aws_access_key_id ${AWS_CI_ACCESS_KEY_ID} --profile ci \
          && aws configure set aws_secret_access_key ${AWS_CI_SECRET_ACCESS_KEY} --profile ci \
          && aws configure set aws_account_id ${AWS_QA_ACCOUNT_ID} --profile qa \
          && aws configure set aws_access_key_id ${AWS_QA_ACCESS_KEY_ID} --profile qa \
          && aws configure set aws_secret_access_key ${AWS_QA_SECRET_ACCESS_KEY} --profile qa \

      #Enviroment CI
      - name: Setup ECR enviromment CI 
        run: |
          docker login \
          -u AWS \
          -p $(aws ecr --profile ci get-login-password) \
          https://$AWS_CI_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      - name: Parse Json and set env 
        run: |
          echo "IMAGE_NAME=$(cat ./images-docker/images.json | jq '.[].Image' | sed 's/"//g')" >> $GITHUB_ENV \
          && echo "DOCKER_URI=$(cat ./images-docker/images.json | jq '.[].Tag' | sed 's/"//g')" >> $GITHUB_ENV 
      
      - name: Docker pull image 
        run: |
          docker pull $IMAGE_NAME
        
      - name: Docker tag in the ECS
        run: |
          docker tag $IMAGE_NAME $DOCKER_URI

      - name: Push to ECR
        run: |
          docker push $DOCKER_URI
